# Server configuration
[server]
webhook_url = "https://bot.jprq.site"
port = 8080

# Telegram configuration
[telegram]
bot_token = "6591091545:AAF8EMR90Bb5FcD0qzsyzosj1B9BqKFLEPQ"

# Database configuration
[postgres]
host = "localhost"
port = 5555
user = "youruser"
password = "yourpassword"
dbname = "yourdb"
sslmode = "disable"
